name: Deploy Next.js Portfolio

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


jobs:
  # ===== CI: Build & Test =====
  build:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/minhanh2610/minhanh-portfolio:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
  
  # ===== CD: Build & Deploy =====
  deploy:
    runs-on: self-hosted
    
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
    - name: Deploy to Proxmox
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.102 # IP of your nextjs-portfolio CT
        username: root
        key: ${{ secrets.PROXMOX_SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /root/portfolio
          cd /root/portfolio
          
          echo "version: '3'" > docker-compose.yml
          echo "services:" >> docker-compose.yml
          echo "  portfolio:" >> docker-compose.yml
          echo "    image: ghcr.io/minhanh2610/minhanh-portfolio:latest" >> docker-compose.yml
          echo "    container_name: minhanh-portfolio" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '3000:3000'" >> docker-compose.yml
          echo "    restart: always" >> docker-compose.yml
          docker-compose pull
          docker-compose up -d
